# 是否开启
enable: false
# 权限列表
perm:
  - island.player
# 白名单玩家
white-list:
  - windy
# 踢出时的消息
message: "&c空岛玩家或无权限玩家禁止进入资源服"
#调试模式
debug: true
#Placeholder变量判断是否启用
enable-placeholder: false
#Placeholder变量，只能是返回布尔值的
placeholder:
  - '%iridiumSkyblock_current_island_owner%'

#执行命令
placeholder-commands:
  - 'lp user %player_name% permission set island.player true'

